"""
region_props.py  —  place in object_classification/

Works with the NEW patch-based pipeline.
Loads pre-computed class_map.npy and confidence_map.npy
generated by generate_map.py. Does NOT load X_cleaned.npy.
"""
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from skimage import measure, morphology
import json
import os

# ── Configuration ─────────────────────────────────────────────────────
# After background masking, model indices are:
#   0 = Healthy   (raw label 1.0)
#   1 = Stressed  (raw label 2.0)
#   2 = Diseased  (raw label 3.0)
#
# So MIN_DISEASE_CLASS = 1 means "Stressed or Diseased"
# Set to 2 if you only want confirmed Diseased regions flagged.
MIN_DISEASE_CLASS = 1    # model index >= this = disease/stress
MIN_CONFIDENCE    = 0.65  # only flag pixels the model is ≥65% sure about
MIN_REGION_AREA   = 1500  # ignore tiny specks below this pixel count
# ──────────────────────────────────────────────────────────────────────


def classify_regions():
    print("--- Disease Region Detection ---")

    # ── Load label map to get class names ─────────────────────────
    class_names = {0: 'Healthy', 1: 'Stressed', 2: 'Diseased'}  # defaults
    if os.path.exists('models/label_map.json'):
        with open('models/label_map.json') as f:
            lm = json.load(f)
        reverse_map = {int(k): float(v) for k, v in lm['reverse_map'].items()}
        raw_to_name = {
            1.0: 'Healthy',
            2.0: 'Stressed',
            3.0: 'Diseased',
        }
        class_names = {
            idx: raw_to_name.get(reverse_map.get(idx, 0), f"Class {idx}")
            for idx in reverse_map
        }

    # ── Load pre-computed maps from generate_map.py ───────────────
    # generate_map.py saves these — run it first
    if not (os.path.exists('results/class_map.npy') and
            os.path.exists('results/confidence_map.npy')):
        print("❌ results/class_map.npy or confidence_map.npy not found.")
        print("   Run generate_map.generate_stress_map() first.")
        return

    print("Loading pre-computed class and confidence maps...")
    class_map      = np.load('results/class_map.npy')
    confidence_map = np.load('results/confidence_map.npy')
    H, W           = class_map.shape
    print(f"   Map size: {H} × {W}")

    # ── Build disease mask ────────────────────────────────────────
    # A pixel is flagged only if:
    #   1. model index >= MIN_DISEASE_CLASS (not healthy)
    #   2. confidence >= MIN_CONFIDENCE (model is sure)
    disease_mask = (
        (class_map >= MIN_DISEASE_CLASS) &
        (confidence_map >= MIN_CONFIDENCE)
    ).astype(np.uint8)

    total_plant   = (class_map >= 0).sum()
    disease_count = disease_mask.sum()
    print(f"   High-confidence disease pixels : {disease_count:,}")
    print(f"   Total pixels                   : {total_plant:,}")
    print(f"   Disease coverage               : {disease_count/total_plant*100:.1f}%")

    if disease_count == 0:
        print("   ⚠ No disease regions found.")
        print(f"   Try lowering MIN_CONFIDENCE (currently {MIN_CONFIDENCE})")
        return

    # ── Morphological cleanup ─────────────────────────────────────
    print("Cleaning up noise with morphological operations...")
    cleaned = morphology.opening(disease_mask, morphology.square(5))
    cleaned = morphology.closing(cleaned, morphology.square(30))

    # ── Find connected regions ────────────────────────────────────
    labels = measure.label(cleaned, connectivity=2)
    props  = measure.regionprops(labels)

    significant = [p for p in props if p.area > MIN_REGION_AREA]
    significant.sort(key=lambda x: x.area, reverse=True)

    print(f"   Raw regions: {len(props)}  →  "
          f"Significant (>{MIN_REGION_AREA}px): {len(significant)}")

    # ── Severity scoring ──────────────────────────────────────────
    def severity(prop):
        r0, c0, r1, c1 = prop.bbox
        patch_conf  = confidence_map[r0:r1, c0:c1]
        patch_class = class_map[r0:r1, c0:c1]
        mask = patch_class >= MIN_DISEASE_CLASS
        return float(patch_conf[mask].mean()) if mask.sum() > 0 else 0.0

    severity_thresholds = [
        (0.70, 'yellow',  'Low'),
        (0.80, 'orange',  'Moderate'),
        (0.90, 'red',     'High'),
        (1.01, 'darkred', 'Critical'),
    ]

    def get_colour_level(sev):
        for thresh, colour, level in severity_thresholds:
            if sev < thresh:
                return colour, level
        return 'darkred', 'Critical'

    # ── Visualise ─────────────────────────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    fig.suptitle(
        f"Disease Region Detection — {len(significant)} significant areas",
        fontsize=13, fontweight='bold'
    )

    axes[0].imshow(class_map, cmap='RdYlGn_r',
                   vmin=0, vmax=max(int(class_map.max()), 2))
    axes[0].set_title("Class Prediction Map", fontsize=11)
    axes[0].axis('off')

    axes[1].imshow(confidence_map, cmap='viridis', vmin=0, vmax=1)
    axes[1].set_title("Confidence Map with Disease Regions", fontsize=11)
    axes[1].axis('off')

    for i, prop in enumerate(significant):
        r0, c0, r1, c1 = prop.bbox
        sev = severity(prop)
        colour, level = get_colour_level(sev)

        for ax in axes:
            ax.add_patch(mpatches.Rectangle(
                (c0, r0), c1 - c0, r1 - r0,
                fill=False, edgecolor=colour, linewidth=2
            ))
            if i < 8:
                ax.text(
                    c0 + 3, r0 - 6,
                    f"#{i+1} {level} ({sev:.0%})",
                    color='white', fontsize=8, fontweight='bold',
                    bbox=dict(facecolor=colour, alpha=0.7, pad=1)
                )

    legend_patches = [
        mpatches.Patch(color='yellow',  label='Low (<70%)'),
        mpatches.Patch(color='orange',  label='Moderate (70–80%)'),
        mpatches.Patch(color='red',     label='High (80–90%)'),
        mpatches.Patch(color='darkred', label='Critical (>90%)'),
    ]
    axes[1].legend(handles=legend_patches, loc='lower right',
                   fontsize=8, framealpha=0.8)

    plt.tight_layout()
    os.makedirs('results', exist_ok=True)
    out = 'results/final_detection_clean.png'
    plt.savefig(out, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"   ✔ Detection map → {out}")

    # ── Summary table ─────────────────────────────────────────────
    print(f"\n   {'#':<5} {'Area (px)':<12} {'Severity':<12} {'Confidence'}")
    print("   " + "─" * 44)
    for i, prop in enumerate(significant[:10]):
        sev = severity(prop)
        _, level = get_colour_level(sev)
        print(f"   {i+1:<5} {prop.area:<12,} {level:<12} {sev:.1%}")


if __name__ == "__main__":
    classify_regions()